packages:
  - apps/**
  - packages/**
autoInstallPeers: true
catalog:
  typescript: 6.0.2
  oxfmt: 0.36.0
  oxlint: 1.47.0
  tailwindcss: 4.2.2
  monaco-vim: ^0.4.4
  "@types/node": ^24.6.0
  "@types/vscode": ^1.95.0
  "@vscode/vsce": ^3.6.2
  vscode-languageclient: ^9.0.1
disallowWorkspaceCycles: true
engineStrict: true
linkWorkspacePackages: true
